version: '3.4'

services:
  adaptai-backend:
    image: adaptaiacr.azurecr.io/adaptai-backend:prod
    build:
      context: .
      dockerfile: ./Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    environment:
      - OPENAI_KEY
      - PERPLEXITY_KEY
      - DEEPL_KEY
      - ELEVENLABS_KEY
      - AYRSHARE_TOKEN
      - AYRSHARE_KEY
      - AZURE_ACCOUNT_KEY
      - ALPHA_VANTAGE_API_KEY
      - AZURE_POSTGRESQL_CONNECTIONSTRING
      - RUNNING_IN_PRODUCTION=1