# Generated by Django 5.0.3 on 2025-04-16 17:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_post_id', models.CharField(max_length=250, verbose_name='platform post id')),
                ('url', models.CharField(max_length=250, verbose_name='url')),
                ('platform', models.CharField(max_length=50, verbose_name='platform')),
                ('ayrshare_id', models.CharField(max_length=250, verbose_name='ayrshare id')),
                ('ref_id', models.CharField(max_length=250, verbose_name='ref id')),
                ('status', models.CharField(max_length=20, verbose_name='status')),
                ('message_error', models.TextField(null=True, verbose_name='message error')),
                ('text', models.TextField(verbose_name='text')),
                ('image', models.CharField(max_length=250, null=True, verbose_name='image')),
                ('send_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='send date')),
                ('send_local_date', models.DateTimeField(default=None, null=True, verbose_name='send local date')),
                ('post_date', models.DateTimeField(default=None, null=True, verbose_name='post date')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='upload/ayrshare/')),
                ('image_url', models.URLField(blank=True, null=True)),
                ('date_create', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date create')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ayrshare_images', to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_image', to='api_ayrshare.posts', verbose_name='post')),
            ],
        ),
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=250, verbose_name='key')),
                ('name', models.CharField(max_length=250, verbose_name='name')),
                ('ref_id', models.CharField(max_length=250, verbose_name='ref id')),
                ('description', models.CharField(blank=True, max_length=250, null=True, verbose_name='description')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
        migrations.AddField(
            model_name='posts',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='api_ayrshare.profiles', verbose_name='profile'),
        ),
    ]
