# Generated by Django 5.0.3 on 2025-04-17 20:34

import api_ayrshare.models.image_upload
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_ayrshare', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageupload',
            name='image_url',
        ),
        migrations.AlterField(
            model_name='imageupload',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=api_ayrshare.models.image_upload.user_upload_path),
        ),
    ]
