# Generated by Django 5.0.3 on 2025-07-21 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_company_admin',
            field=models.BooleanField(default=False),
        ),
    ]
