# Generated by Django 5.0.3 on 2025-03-21 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ESGArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(choices=[('Evoluzione del contesto normativo', 'Evoluzione del contesto normativo'), ('News reati informativi', 'News reati informativi'), ('Responsabilità amministratori', 'Responsabilità amministratori'), ('Rischi reputazionali', 'Rischi reputazionali')], max_length=100)),
                ('title', models.CharField(max_length=250)),
                ('author', models.CharField(default='Sconosciuto', max_length=100)),
                ('summary', models.TextField()),
                ('source', models.CharField(max_length=150)),
                ('url', models.URLField()),
                ('language', models.CharField(default='Italian', max_length=30)),
                ('date_published', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
