# Generated by Django 5.0.3 on 2025-03-25 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_esgarticle'),
    ]

    operations = [
        migrations.CreateModel(
            name='CEOArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personality', models.CharField(choices=[('Mario Rossi', 'Mario Rossi'), ('Elvira Giacomelli', 'Elvira Giacomelli'), ('Luigi Farris', 'Luigi Farris')], max_length=100)),
                ('title', models.CharField(max_length=250)),
                ('author', models.CharField(default='Sconosciuto', max_length=100)),
                ('content', models.TextField()),
                ('source', models.CharField(max_length=150)),
                ('url', models.URLField()),
                ('language', models.CharField(default='Italian', max_length=30)),
                ('date_published', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
