# Generated by Django 5.0.3 on 2025-03-25 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_ceoarticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='ceoarticle',
            name='sentiment',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
