# Generated by Django 5.0.3 on 2025-03-28 14:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_conversation_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Conversation',
            new_name='ChatConversation',
        ),
        migrations.RenameModel(
            old_name='Message',
            new_name='ChatMessage',
        ),
    ]
