# Generated by Django 5.0.3 on 2025-03-31 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_chatmessage_file_chatmessage_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='image_url',
        ),
    ]
