# Generated by Django 5.0.3 on 2025-04-01 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_chatmessage_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='file',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='file_url',
        ),
    ]
