# Generated by Django 5.0.3 on 2025-04-02 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_chatmessage_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatconversation',
            name='id',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
    ]
