# Generated by Django 5.0.3 on 2025-04-02 18:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_chatconversation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatconversation',
            name='id',
            field=models.CharField(default=uuid.uuid4, max_length=40, primary_key=True, serialize=False),
        ),
    ]
