# Generated by Django 5.0.3 on 2025-04-02 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_chatconversation_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='esgarticle',
            name='viewed',
            field=models.BooleanField(default=False),
        ),
    ]
