# Generated by Django 5.0.3 on 2025-04-03 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_esgarticle_viewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='ceoarticle',
            name='viewed',
            field=models.BooleanField(default=False),
        ),
    ]
