# Generated by Django 5.0.3 on 2025-04-11 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_ceoarticle_viewed'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitorSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Competitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=255)),
                ('logo', models.URLField()),
                ('sectors', models.JSONField()),
                ('description', models.TextField()),
                ('website', models.URLField()),
                ('search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitors', to='core.competitorsearch')),
            ],
        ),
    ]
