# Generated by Django 5.0.3 on 2025-04-11 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_competitorsearch_competitor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competitor',
            old_name='company',
            new_name='competitor',
        ),
        migrations.AddField(
            model_name='competitorsearch',
            name='company_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
