# Generated by Django 5.0.3 on 2025-04-11 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_rename_company_competitor_competitor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketNewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('sector', 'Sector'), ('competitors', 'Competitors')], max_length=12)),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('date_published', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
