# Generated by Django 5.0.3 on 2025-04-12 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_marketnewsarticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitorsearch',
            name='sector',
            field=models.CharField(default='Technology', max_length=255),
        ),
    ]
