# Generated by Django 5.0.3 on 2025-04-12 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_competitorsearch_sector'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyMarketReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.TextField()),
            ],
        ),
    ]
