# Generated by Django 5.0.3 on 2025-04-12 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_companymarketreport'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companymarketreport',
            old_name='company_name',
            new_name='company',
        ),
    ]
