# Generated by Django 5.0.3 on 2025-04-12 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_rename_company_name_companymarketreport_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='companymarketreport',
            name='citations',
            field=models.TextField(blank=True, null=True),
        ),
    ]
