# Generated by Django 5.0.3 on 2025-04-13 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_companymarketreport_citations'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyStockData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=50)),
                ('stock_symbol', models.CharField(max_length=20)),
                ('stock_exchange', models.CharField(max_length=20)),
                ('stock_price_today_usd', models.FloatField(blank=True, null=True)),
                ('stock_price_today_eur', models.FloatField(blank=True, null=True)),
                ('market_cap_usd', models.CharField(blank=True, max_length=50, null=True)),
                ('market_cap_eur', models.CharField(blank=True, max_length=50, null=True)),
                ('pe_ratio', models.FloatField(blank=True, null=True)),
                ('sector', models.CharField(blank=True, max_length=50, null=True)),
                ('stock_volatility_level', models.CharField(blank=True, max_length=50, null=True)),
                ('short_term_forecast', models.TextField(blank=True, null=True)),
                ('possible_risk_factors', models.TextField(blank=True, null=True)),
                ('latest_news', models.TextField(blank=True, null=True)),
                ('analyst_recommendation', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
