# Generated by Django 5.0.3 on 2025-04-13 23:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_companystockdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='companystockdata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
