# Generated by Django 5.0.3 on 2025-04-14 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_companystockdata_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyQuarterlyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('quarter', models.CharField(choices=[('Q1', 'Q1'), ('Q2', 'Q2'), ('Q3', 'Q3'), ('Q4', 'Q4')], max_length=2)),
                ('year', models.PositiveIntegerField()),
                ('press_release', models.URLField()),
                ('financial_statements', models.URLField()),
                ('form_10k', models.URLField(blank=True, null=True)),
                ('insight_report', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-year', '-quarter'],
            },
        ),
    ]
