# Generated by Django 5.0.3 on 2025-04-24 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_companyquarterlyreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esgarticle',
            name='topic',
            field=models.CharField(choices=[('Evoluzione del contesto normativo', 'Evoluzione del contesto normativo'), ('Reati informativi', 'Reati informativi'), ('Responsabilità amministratori', 'Responsabilità amministratori'), ('Rischi reputazionali', 'Rischi reputazionali')], max_length=100),
        ),
    ]
