# Generated by Django 5.0.3 on 2025-05-12 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_companyinfo_ceo_competitorinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyquarterlyreport',
            name='financial_statements',
        ),
        migrations.RemoveField(
            model_name='companyquarterlyreport',
            name='form_10k',
        ),
        migrations.RemoveField(
            model_name='companyquarterlyreport',
            name='press_release',
        ),
        migrations.AddField(
            model_name='companyquarterlyreport',
            name='citations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='competitorinfo',
            name='stock_symbol',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
