# Generated by Django 5.0.3 on 2025-05-14 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_remove_companyquarterlyreport_financial_statements_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='citations',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
