# Generated by Django 5.0.3 on 2025-05-14 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_chatmessage_citations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ceoarticle',
            name='personality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='core.ceo'),
        ),
    ]
