# Generated by Django 5.0.3 on 2025-05-15 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_ceoarticle_personality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatconversation',
            name='name',
            field=models.CharField(default=None, max_length=100, unique=True),
        ),
    ]
