# Generated by Django 5.0.3 on 2025-07-17 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_generateddocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyRouteRestriction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restricted_routes', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.companyinfo')),
            ],
        ),
    ]
