# Generated by Django 5.0.3 on 2025-07-18 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_masterroutelist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ceo',
            options={'verbose_name': 'CEO', 'verbose_name_plural': 'CEOs'},
        ),
        migrations.AlterModelOptions(
            name='ceoarticle',
            options={'verbose_name': 'Article - CEO', 'verbose_name_plural': 'Articles - CEO'},
        ),
        migrations.AlterModelOptions(
            name='chatconversation',
            options={'verbose_name': 'Chat - Conversation', 'verbose_name_plural': 'Chat - Conversations'},
        ),
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'verbose_name': 'Chat - Message', 'verbose_name_plural': 'Chat - Messages'},
        ),
        migrations.AlterModelOptions(
            name='companyinfo',
            options={'verbose_name': 'Company - Info', 'verbose_name_plural': 'Companies - Info'},
        ),
        migrations.AlterModelOptions(
            name='companymarketreport',
            options={'verbose_name': 'Company - Market Report', 'verbose_name_plural': 'Companies - Market Reports'},
        ),
        migrations.AlterModelOptions(
            name='companyquarterlyreport',
            options={'ordering': ['-year', '-quarter'], 'verbose_name': 'Company - Quarterly Report', 'verbose_name_plural': 'Companies - Quarterly Reports'},
        ),
        migrations.AlterModelOptions(
            name='companyrouterestriction',
            options={'verbose_name': 'Company - Route Restriction', 'verbose_name_plural': 'Companies - Route Restrictions'},
        ),
        migrations.AlterModelOptions(
            name='companystockdata',
            options={'verbose_name': 'Company - Stock Data', 'verbose_name_plural': 'Companies - Stock Data'},
        ),
        migrations.AlterModelOptions(
            name='competitorinfo',
            options={'verbose_name': 'Competitor - Info', 'verbose_name_plural': 'Competitors - Info'},
        ),
        migrations.AlterModelOptions(
            name='competitorsearch',
            options={'verbose_name': 'Competitor - Search', 'verbose_name_plural': 'Competitors - Search'},
        ),
        migrations.AlterModelOptions(
            name='esgarticle',
            options={'verbose_name': 'Article - ESG', 'verbose_name_plural': 'Articles - ESG'},
        ),
        migrations.AlterModelOptions(
            name='marketnewsarticle',
            options={'verbose_name': 'Article - Market News', 'verbose_name_plural': 'Articles - Market News'},
        ),
        migrations.AlterModelOptions(
            name='masterroutelist',
            options={'verbose_name': 'Frontend - Master Route List', 'verbose_name_plural': 'Frontend - Master Route Lists'},
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='sector',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='stock_symbol',
            field=models.CharField(blank=True, max_length=32, unique=True),
        ),
    ]
