# Generated by Django 5.0.3 on 2025-07-18 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_alter_ceo_options_alter_ceoarticle_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinfo',
            name='stock_symbol',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
