# Generated by Django 5.0.3 on 2025-07-21 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_alter_companyinfo_stock_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketnewsarticle',
            name='company_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='market_articles_fk', to='core.companyinfo'),
        ),
    ]
