# Generated by Django 5.0.3 on 2025-07-21 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_ceoarticle_company_marketnewsarticle_company_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ceoarticle',
            name='company',
        ),
    ]
