# Generated by Django 5.0.3 on 2025-07-21 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_remove_ceoarticle_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatconversation',
            name='name',
            field=models.CharField(default='New Chat', max_length=100),
        ),
    ]
