# Generated by Django 5.0.3 on 2025-07-21 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_alter_chatconversation_name'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='chatconversation',
            name='unique_conversation_name',
        ),
    ]
