# Generated by Django 5.0.3 on 2025-07-24 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_remove_chatconversation_unique_conversation_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competitorinfo',
            old_name='sector',
            new_name='sectors_company',
        ),
        migrations.AddField(
            model_name='competitorinfo',
            name='created_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='competitorinfo',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='competitorinfo',
            name='logo',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='competitorinfo',
            name='sectors_competitor',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='competitorinfo',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitors', to='core.companyinfo'),
        ),
    ]
