# Generated by Django 5.0.3 on 2025-07-25 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_rename_sector_competitorinfo_sectors_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinfo',
            name='sector',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='competitorinfo',
            name='sectors_company',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
