# Generated by Django 5.2.3 on 2025-09-25 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_companyinfo_sources_marketnewsarticle_company_fk'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['created_at'], 'verbose_name': 'Chat - Message', 'verbose_name_plural': 'Chat - Messages'},
        ),
        migrations.AddField(
            model_name='chatconversation',
            name='is_new',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='AssistantThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread_id', models.CharField(max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='core.chatconversation')),
            ],
            options={
                'verbose_name': 'Chat - Thread',
                'verbose_name_plural': 'Chat - Threads',
            },
        ),
    ]
