# Generated by Django 5.2.4 on 2025-10-16 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_alter_chatmessage_options_chatconversation_is_new_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ceoarticle',
            name='author',
            field=models.CharField(blank=True, default='Sconosciuto', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ceoarticle',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ceoarticle',
            name='date_published',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ceoarticle',
            name='language',
            field=models.CharField(blank=True, default='Italian', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='ceoarticle',
            name='source',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='ceoarticle',
            name='url',
            field=models.URLField(unique=True),
        ),
    ]
