# Generated by Django 5.2.4 on 2025-10-16 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_alter_ceo_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='CEOConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_id', models.CharField(blank=True, help_text='ID da conversa usado para manter o contexto com a OpenAI.', max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ceo', models.ForeignKey(help_text='CEO associado a esta conversa.', on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='core.ceo')),
                ('company', models.ForeignKey(help_text='Empresa associada à conversa.', on_delete=django.db.models.deletion.CASCADE, related_name='ceo_conversations', to='core.companyinfo')),
            ],
            options={
                'verbose_name': 'CEO Conversation',
                'verbose_name_plural': 'CEO Conversations',
                'unique_together': {('company', 'ceo')},
            },
        ),
    ]
