# Generated by Django 5.2.4 on 2025-10-16 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_ceo_conversation'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ceoarticle',
            unique_together={('title', 'personality')},
        ),
    ]
