# Generated by Django 5.2.4 on 2025-10-23 12:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_unique_together_ceoarticle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkedinScheduledPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='linkedin_scheduled/%Y/%m/%d/')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(help_text='Empresa associada ao post', on_delete=django.db.models.deletion.CASCADE, related_name='linkedin_scheduled_posts', to='core.companyinfo')),
                ('created_by', models.ForeignKey(blank=True, help_text='Usuário que criou o agendamento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linkedin_scheduled_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'LinkedIn Scheduled Post',
                'verbose_name_plural': 'LinkedIn Scheduled Posts',
            },
        ),
    ]
