# Generated by Django 5.2.4 on 2025-10-23 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_linkedin_scheduled_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linkedinscheduledpost',
            name='image',
        ),
        migrations.AddField(
            model_name='linkedinscheduledpost',
            name='image_base64',
            field=models.TextField(blank=True, help_text='Base64 encoded image data (data:<mime>;base64,<payload>)', null=True),
        ),
    ]
