# Generated by Django 5.0.3 on 2025-10-31 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_remove_linkedinscheduledpost_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='sector_keywords',
            field=models.JSONField(blank=True, default=list, help_text="List of keywords describing the company's sector.", null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='sector_websites',
            field=models.JSONField(blank=True, default=list, help_text='List of custom URLs provided by the user for sector intelligence.', null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='sources',
            field=models.TextField(blank=True, help_text='List of URLs from reliable sources for reports, one per line.', null=True),
        )
    ]
