# Generated by Django 5.0.3 on 2025-10-31 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_companyinfo_sector_keywords_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketnewsarticle',
            name='category',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='marketnewsarticle',
            name='company_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='market_articles_fk', to='core.companyinfo'),
        ),
        migrations.AddField(
            model_name='marketnewsarticle',
            name='relevance',
            field=models.CharField(blank=True, choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='marketnewsarticle',
            name='type',
            field=models.CharField(choices=[('sector', 'Sector'), ('competitor', 'Competitor'), ('client', 'Client'), ('fornitori', 'Fornitori')], max_length=12),
        ),
        migrations.CreateModel(
            name='MarketNewsSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_configured', models.BooleanField(default=False)),
                ('configured_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='marketing_news_setup', to='core.companyinfo')),
            ],
            options={
                'verbose_name': 'Marketing News Setup',
                'verbose_name_plural': 'Marketing News Setups',
            },
        ),
    ]
