# Generated by Django 5.0.3 on 2025-11-03 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_marketnewsarticle_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatedCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('competitor', 'Competitor'), ('client', 'Client'), ('fornitori', 'Fornitori')], max_length=16)),
                ('name', models.CharField(max_length=255)),
                ('stock_symbol', models.CharField(blank=True, max_length=32)),
                ('website', models.URLField(blank=True, null=True)),
                ('logo', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('sectors', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_companies', to='core.companyinfo')),
            ],
            options={
                'verbose_name': 'Related Company',
                'verbose_name_plural': 'Related Companies',
            },
        ),
        migrations.DeleteModel(
            name='CompetitorInfo',
        ),
    ]
