# Generated by Django 5.0.3 on 2025-11-04 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_relatedcompany_delete_competitorinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SummaryNewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('sector', 'Sector'), ('competitor', 'Competitor'), ('client', 'Client'), ('fornitori', 'Fornitori')], max_length=12)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('relevance', models.CharField(blank=True, choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=6, null=True)),
                ('sources_urls', models.URLField(blank=True, default=list)),
                ('company_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='market_summary_articles_fk', to='core.companyinfo')),
            ],
            options={
                'verbose_name': 'Summary Article - Market News',
                'verbose_name_plural': 'Summary Articles - Market News',
            },
        ),
    ]
