# Generated by Django 5.0.3 on 2025-11-05 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_summarynewsarticle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marketnewsarticle',
            options={'verbose_name': 'Market News - Article', 'verbose_name_plural': 'Market News - Articles'},
        ),
        migrations.AlterModelOptions(
            name='summarynewsarticle',
            options={'verbose_name': 'Market News - Summary Article', 'verbose_name_plural': 'Market News - Summary Articles'},
        ),
    ]
