# Generated by Django 5.0.3 on 2025-11-05 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_alter_marketnewsarticle_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketNewsAlertPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('category', models.CharField(choices=[('sector', 'Sector'), ('competitors', 'Competitors'), ('clients', 'Clients'), ('fornitori', 'Fornitori')], max_length=16)),
                ('enabled', models.BooleanField(default=True)),
                ('relevance', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='high', max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_preferences', to='core.companyinfo')),
            ],
            options={
                'verbose_name': 'Market News - Alert Preference',
                'verbose_name_plural': 'Market News - Alert Preferences',
            },
        ),
    ]
