# Generated by Django 5.0.3 on 2025-11-05 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_marketnewsalertpreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketnewssetup',
            name='conversation_id_mi01',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='marketnewssetup',
            name='conversation_id_mi02',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='marketnewssetup',
            name='conversation_id_mi03',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='marketnewssetup',
            name='conversation_id_mi04',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
