# Generated by Django 5.0.3 on 2025-11-06 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_marketnewssetup_conversation_id_mi01_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summarynewsarticle',
            name='sources_urls',
            field=models.TextField(blank=True, default=''),
        ),
    ]
