# Generated by Django 5.0.3 on 2025-11-06 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_summarynewsarticle_sources_urls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketnewsarticle',
            name='url',
            field=models.URLField(max_length=1000),
        ),
    ]
