# Generated by Django 5.0.3 on 2025-11-10 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_esgmonthlyreport'),
    ]

    operations = [
        migrations.RenameField(
            model_name='esgarticle',
            old_name='summary',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='esgarticle',
            name='author',
        ),
        migrations.RemoveField(
            model_name='esgarticle',
            name='language',
        ),
        migrations.RemoveField(
            model_name='esgarticle',
            name='source',
        ),
        migrations.RemoveField(
            model_name='esgarticle',
            name='viewed',
        ),
        migrations.AlterField(
            model_name='esgarticle',
            name='url',
            field=models.URLField(max_length=500),
        ),
    ]
