# Generated by Django 5.2.4 on 2025-12-09 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0063_ceoarticle_personality_url_unique"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeatureUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "module",
                    models.CharField(
                        choices=[("earnings", "Earnings Call")],
                        default="earnings",
                        max_length=50,
                    ),
                ),
                (
                    "feature",
                    models.CharField(
                        choices=[
                            ("traduttore", "Traduttore"),
                            ("crea_speech", "Crea speech"),
                            ("trascrizione_audio", "Trascrizione audio"),
                        ],
                        max_length=50,
                    ),
                ),
                ("count", models.PositiveIntegerField(default=0)),
                (
                    "max_limit",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Optional max uses allowed for this feature per period/company",
                        null=True,
                    ),
                ),
                ("last_used", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feature_usages",
                        to="core.companyinfo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Feature usage",
                "verbose_name_plural": "Features usage",
                "unique_together": {("module", "feature", "company")},
            },
        ),
    ]
