# Generated by Django 5.2.4 on 2025-12-10 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0064_featureusage"),
    ]

    operations = [
        migrations.AddField(
            model_name="ceo",
            name="additional_info",
            field=models.TextField(blank=True, null=True),
        )
    ]
