# Generated by Django 5.2.4 on 2026-03-06 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0066_glossaryentry"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DeepLGlossaryReference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deepl_glossary_id",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                ("glossary_name", models.CharField(max_length=255)),
                ("scope", models.CharField(default="company", max_length=10)),
                ("language_pairs", models.JSONField(blank=True, default=list)),
                ("entry_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_synced_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "DeepL Glossary Reference",
                "verbose_name_plural": "DeepL Glossary References",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.RenameIndex(
            model_name="glossaryentry",
            new_name="core_glossa_company_460a82_idx",
            old_name="core_glossa_company_9001dd_idx",
        ),
        migrations.RenameIndex(
            model_name="glossaryentry",
            new_name="core_glossa_company_7bdea6_idx",
            old_name="core_glossa_company_8641c1_idx",
        ),
        migrations.RenameIndex(
            model_name="glossaryentry",
            new_name="core_glossa_created_965a11_idx",
            old_name="core_glossa_created_4abf8f_idx",
        ),
        migrations.AddField(
            model_name="deeplglossaryreference",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="deepl_glossaries",
                to="core.companyinfo",
            ),
        ),
        migrations.AddField(
            model_name="deeplglossaryreference",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="deepl_glossaries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="deeplglossaryreference",
            index=models.Index(
                fields=["company", "scope"], name="core_deeplg_company_d06284_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="deeplglossaryreference",
            index=models.Index(
                fields=["created_by", "scope"], name="core_deeplg_created_6e59ec_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="deeplglossaryreference",
            index=models.Index(
                fields=["deepl_glossary_id"], name="core_deeplg_deepl_g_c18e5f_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="deeplglossaryreference",
            unique_together={("company", "created_by", "scope")},
        ),
    ]
